version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  vault:
    image: vault:latest
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: devopsrob
      VAULT_DEV_LISTEN_ADDRESS: 127.0.0.1:8200
    ports:
      - "8200:8200"
      - "8201:8201"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 1m30s
      timeout: 10s
      retries: 3
